"""Reorganize models: separate files, rename tables to plural, change completed to status

Revision ID: fe0470f7e3cf
Revises: 
Create Date: 2026-03-07 12:43:31.597276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe0470f7e3cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Rename table 'category' to 'categories'
    op.rename_table('category', 'categories')
    
    # Rename table 'task' to 'tasks'
    op.rename_table('task', 'tasks')
    
    # Alter tasks table: drop old columns and add status
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('completed')
        batch_op.drop_column('due_date')
        batch_op.drop_column('priority')
        batch_op.add_column(sa.Column('status', sa.String(20), nullable=False, server_default='pendiente'))
        # Update foreign key reference from category.id to categories.id
        batch_op.drop_constraint('tasks_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key('tasks_ibfk_2', 'categories', ['category_id'], ['id'])
    
    # Update categories unique constraint name
    with op.batch_alter_table('categories', schema=None) as batch_op:
        pass  # The constraint remains the same, just in the new table name
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Restore 'categories' to 'category'
    op.rename_table('categories', 'category')
    
    # Restore 'tasks' to 'task'
    op.rename_table('tasks', 'task')
    
    # Alter task table: remove status and restore old columns
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True, server_default=False))
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(20), nullable=True, server_default='medium'))
        batch_op.drop_column('status')
        # Restore foreign key reference
        batch_op.drop_constraint('task_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key('task_ibfk_2', 'category', ['category_id'], ['id'])
    
    # ### end Alembic commands ###
